---
- name: Configure prometheus
  tags:
    - configure
    - configure_prometheus
    - prometheus
  block:
    # Configurations
    - name: Send file prometheus configs
      ansible.builtin.template:
        mode: "0644"
        src: prometheus.yml.j2
        dest: "{{ install_prometheus_config_path }}/prometheus.yml"
        owner: prometheus
        group: prometheus
      become: true
      notify:
        - Restart prometheus service
      register: prometheus_config_file

- name: Configure goss
  tags:
    - configure
    - configure_prometheus
    - prometheus
    - configure_goss
    - goss
  block:
    - name: Include Goss add file role
      ansible.builtin.include_role:
        name: install_goss
