---
- name: Install prometheus
  tags:
    - install
    - install_prometheus
    - prometheus
  block:
    # Create System User and group
    - name: Create prometheus group
      ansible.builtin.group:
        name: prometheus
        system: true
        state: present
      become: true

    - name: Create prometheus user
      ansible.builtin.user:
        name: prometheus
        comment: prometheus
        group: prometheus
        shell: /sbin/nologin
        system: true
        create_home: false
      become: true

    # Directory setting
    - name: Create prometheus config directory
      ansible.builtin.file:
        path: "{{ install_prometheus_config_path }}"
        state: directory
        mode: "0755"
        owner: prometheus
        group: prometheus
      become: true

    - name: Create prometheus data directory
      ansible.builtin.file:
        path: "{{ install_prometheus_dbdata_path }}"
        state: directory
        mode: "0755"
        owner: prometheus
        group: prometheus
      become: true

    # Download and Install
    - name: Download Prometheus binary
      ansible.builtin.get_url:
        url: "{{ install_prometheus_bin_dl_file }}"
        dest: /tmp/
        mode: "0644"
        owner: prometheus
        group: prometheus
      register: dl_prom_bin
      become: true

    - name: Unarchive Prometheus binary
      ansible.builtin.unarchive:
        src: "{{ dl_prom_bin.dest }}"
        dest: "/tmp/"
        owner: prometheus
        group: prometheus
        remote_src: true
      become: true

    - name: Copy binary files to install path
      ansible.builtin.copy:
        src: "/tmp/{{ install_prometheus_bin_file }}/{{ item }}"
        dest: "{{ install_prometheus_install_path }}/{{ item }}"
        mode: "0744"
        owner: prometheus
        group: prometheus
        remote_src: true
      become: true
      loop:
        - prometheus
        - promtool
      register: prometheus_binary_files

    - name: Send file prometheus.service
      ansible.builtin.template:
        mode: "0644"
        src: prometheus.service.j2
        dest: /etc/systemd/system/prometheus.service
      become: true
      notify:
        - Restart prometheus service
      register: prometheus_service_file
