---
default:
  image: python:3.11
  cache:
    paths:
      - .cache/pip
  before_script:
    - bash install.sh
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo $SSH_PRIVATE_KEY | base64 -d > ~/.ssh/neverneba.key
    - chmod 600 ~/.ssh/neverneba.key
    - ls -la

variables:
  ANSIBLE_HOST_KEY_CHECKING=False: "false"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - playbook
  - test

goss:
  stage: playbook
  variables:
    POST_URL_TO_DISCORD: $CI_JOB_URL
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
  script:
    - "ansible-playbook project/goss.yml \
      -i inventory \
      --vault-password-file $VAULT_PASS \
      --extra-vars post_url_to_discord=$CI_JOB_URL
      "
  artifacts:
    paths:
      - project/output_files/goss_reports/
    untracked: false
    when: always
    expire_in: "30 days"

ansible-lint:
  stage: test
  script: ansible-lint project

yamllint:
  stage: test
  script: yamllint project/

# MR対象のRoleをMoleculeのテスト対象となるように適宜書き換えてください。
# 変更対象外のTaskは削除してください。
# !!!! この運用は変更が予定されており、将来的にはRoleはリポジトリを分割して管理します。!!!!
install_prometheus:
  stage: test
  image: docker:24.0.6
  services:
    - docker:24.0.6-dind
  before_script:
    - apk add --no-cache
      python3 python3-dev py3-pip gcc git curl build-base
      autoconf automake py3-cryptography linux-headers
      musl-dev libffi-dev openssl-dev openssh rsync
    - docker info
    - python3 --version
    - python3 -m pip install ansible molecule-plugins[docker]
    - ansible --version
    - molecule --version
  script:
    # ここを対象のRoleに書き換えてください
    - cd project/roles/install_prometheus && ls -la
    - molecule test

install_node-exporter:
  stage: test
  image: docker:24.0.6
  services:
    - docker:24.0.6-dind
  before_script:
    - apk add --no-cache
      python3 python3-dev py3-pip gcc git curl build-base
      autoconf automake py3-cryptography linux-headers
      musl-dev libffi-dev openssl-dev openssh rsync
    - docker info
    - python3 --version
    - python3 -m pip install ansible molecule-plugins[docker]
    - ansible --version
    - molecule --version
  script:
    # ここを対象のRoleに書き換えてください
    - cd project/roles/install_node-exporter && ls -la
    - molecule test
