---
prometheus_bin_ver:
  "{% for service in services %}\
  {% if service.name | regex_findall('prometheus.*') %}\
  {{ service.custom_fields.version }}\
  {% endif %}\
  {% endfor %}"
prometheus_bin_dist: linux-amd64
prometheus_bin_file:
  "prometheus-{{ prometheus_bin_ver }}.{{ prometheus_bin_dist }}"
prometheus_bin_dl_url:
  https://github.com/prometheus/prometheus/releases/download
prometheus_bin_dl_file:
  "{{ prometheus_bin_dl_url }}\
  /v{{ prometheus_bin_ver }}\
  /{{ prometheus_bin_file }}.tar.gz"

prometheus_install_path: /usr/local/bin
prometheus_config_path: /etc/prometheus
prometheus_sd_file_path: "{{ prometheus_config_path }}/sd_files"

# list
prometheus_listen_ports:
  "{% for service in services %}\
  {% if service.name | regex_findall('prometheus.*') %}\
  {{ service.ports }}\
  {% endif %}\
  {% endfor %}
  "

# list
prometheus_listen_addresses:
  "{% for service in services %}\
  {% if service.name | regex_findall('prometheus.*') %}\
  {{ service.ipaddresses | \
  map(attribute='address', default='0.0.0.0') | \
  map('ansible.utils.ipaddr', 'address') }}\
  {% endif %}\
  {% endfor %}
  "

prometheus_dbdata_path: /var/prometheus/data

netbox_url: http://nev-ke-co-netbox-01.asaasahi.com
netbox_token: ea4562ce173eeefdf002e176663d6e88d8ea020c

# Use in goss_add_file role
goss_dir_path: /usr/local/share/goss/ansible_auto_create
goss_file_name: prometheus.yml
