---
- name: Restart prometheus service
  block:

    - name: Restart service
      ansible.builtin.systemd:
        name: prometheus.service
        state: restarted
        daemon_reload: true
        enabled: true
      become: true
      register: service

    - name: Service assertion
      ansible.builtin.assert:
        that: service.status.ActiveState == "active"
