---
- name: Download grafana gpg key
  ansible.builtin.get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /usr/share/keyrings/grafana.key
    mode: "0644"
  become: true

- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo:
      "deb [signed-by=/usr/share/keyrings/grafana.key] \
      https://apt.grafana.com stable main"
    mode: "0644"
    state: present
  become: true

- name: Install grafana
  ansible.builtin.apt:
    name: grafana
    state: present
    update_cache: true
  become: true
  notify:
    - Restart grafana-server service

- name: Send base grafana config file
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "644"
    owner: grafana
    group: grafana
  become: true
  loop:
    - src: ldap.toml
      dest: /etc/grafana/ldap.toml
    - src: grafana.ini
      dest: /etc/grafana/grafana.ini
