---
- name: Download grafana gpg key
  ansible.builtin.get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /usr/share/keyrings/grafana.key
    mode: "0644"
  become: true

- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo:
      "deb [signed-by=/usr/share/keyrings/grafana.key] \
      https://apt.grafana.com stable main"
    mode: "0644"
    state: present
  become: true

- name: Install grafana
  ansible.builtin.apt:
    name: "grafana={{ install_grafana_version | default('*') }}"
    state: present
    update_cache: true
  become: true
  notify:
    - Restart grafana-server service

- name: Send base grafana config file
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "644"
    owner: grafana
    group: grafana
  become: true
  loop:
    - src: ldap.toml.j2
      dest: /etc/grafana/ldap.toml
    - src: grafana.ini.j2
      dest: /etc/grafana/grafana.ini
  notify: Restart grafana-server service
  register: send_template_files

- name: Test Include role
  ansible.builtin.include_role:
    name: install_goss
