---
- name: Vars setup
  vars:
    ipv4_address_mask_list:
      - "{{ ansible_default_ipv4.address }}"
      - "{{ ansible_default_ipv4.netmask }}"
    primary_ip4: >
      {{ ipv4_address_mask_list | join('/')
      | ansible.utils.ipaddr('ip/prefix') }}

  block:
    - name: Create virtual machine within NetBox
      netbox.netbox.netbox_virtual_machine:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ inventory_hostname }}"
          cluster: "{{ installation_cluster }}"
          platform:
            "{{ ansible_distribution }}{{ ansible_distribution_version }}"
          vcpus: "{{ ansible_processor_cores }}"
          memory: "{{ ansible_memory_mb.real.total }}"
          tenant: "neverneband"
        state: present
      delegate_to: localhost

    - name: Create interface within NetBox
      netbox.netbox.netbox_vm_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          virtual_machine: "{{ inventory_hostname }}"
          name: "{{ ansible_default_ipv4.interface }}"
          mtu: "{{ ansible_default_ipv4.mtu }}"
          mac_address: "{{ ansible_default_ipv4.macaddress }}"
        state: present
      delegate_to: localhost

    - name: Assign IP address interface within NetBox
      netbox.netbox.netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          address: "{{ primary_ip4 }}"
          dns_name: "{{ inventory_hostname }}"
          tenant: "neverneband"
          assigned_object:
            name: "{{ ansible_default_ipv4.interface }}"
            virtual_machine: "{{ inventory_hostname }}"
            # device: 物理筐体はこっち
        state: present
      delegate_to: localhost

    - name: Assign IP address virtual machine within NetBox
      netbox.netbox.netbox_virtual_machine:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ inventory_hostname }}"
          primary_ip4: "{{ primary_ip4 }}"
        state: present
      delegate_to: localhost
