---
- name: Uninstall goss
  tags:
    - uninstall
    - uninstall_goss
    - never
  block:
    - name: Delete all goss directory and files
      ansible.builtin.file:
        path: "{{ goss_base_dir }}"
        state: absent
      become: true

    - name: Delete binary files for goss
      ansible.builtin.file:
        path: "{{ goss_bin_dir }}"
        state: absent
      become: true
