---
- name: Verify node-exporter
  hosts: all
  gather_facts: false

  tasks:
    - name: Get service status
      ansible.builtin.systemd:
        name: node-exporter.service
      register: service_status

    - name: Print service status
      ansible.builtin.debug:
        var: service_status

    - name: Is service state active and enabled
      ansible.builtin.assert:
        that:
          - service_status.status.ActiveState == "active"
          - service_status.status.UnitFileState == "enabled"

    - name: Is port 9100 listen
      ansible.builtin.wait_for:
        host: 127.0.0.1
        port: 9100
        timeout: 10
      register: waitfor

    - name: Print waitfor
      ansible.builtin.debug:
        var: waitfor
