---
- name: Converge
  hosts: all
  tasks:
    - name: "systemctl and sudo install"
      ansible.builtin.apt:
        name: 
          - systemctl
          - sudo
          - openssh-server
        update_cache: true
        state: present

    - name: Create /var/run/sshd
      ansible.builtin.file:
        path: /var/run/sshd
        state: directory

    - name: "Include neverneband.sshd_ldap"
      include_role:
        name: "neverneband.sshd_ldap"
