---
- name: Converge
  hosts: all
  tasks:
    - name: "Install systemctl sudo openssh-server"
      ansible.builtin.apt:
        name:
          - systemctl
          - sudo
          - openssh-server
        update_cache: true
        state: present

    - name: Create /var/run/sshd
      ansible.builtin.file:
        mode: "0755"
        path: /var/run/sshd
        state: directory

    - name: "Include neverneband.sshd_ldap"
      ansible.builtin.include_role:
        name: "neverneband.sshd_ldap"
