---
- name: Incloude install tasks
  ansible.builtin.include_tasks:
    file: install.yml
  tags:
    - install
    - install_node-exporter
    - node-exporter

- name: Incloude configure tasks
  ansible.builtin.include_tasks:
    file: configure.yml
  tags:
    - configure
    - configure_node-exporter
    - node-exporter
    - configure_goss
    - goss

# 将来実装予定
# - name: Incloude uninstall tasks
#   ansible.builtin.include_tasks:
#     file: uninstall.yml
#   tags:
#     - uninstall
#     - uninstall_node-exporter
#     - never
