---
- name: Converge
  hosts: all
  vars:
    goss_sub_dir: /usr/local/share/goss/ansible_auto_create
    goss_file_name: sssd_ldap.yml
    goss_template_file: sssd_ldap_gossfile.j2
  tasks:
    - name: Install systemctl, openssh and sudo
      ansible.builtin.apt:
        name:
          - systemctl
          - sudo
          - openssh-server
        update_cache: true
        state: present

    - name: Create /var/run/sshd
      ansible.builtin.file:
        mode: "0755"
        path: /var/run/sshd
        state: directory

    - name: Include install_sssd_for_ldap
      ansible.builtin.include_role:
        name: install_sssd_for_ldap
