---
- name: Converge
  hosts: all
  tasks:
    - name: "Install systemctl and sudo "
      ansible.builtin.apt:
        name:
          - systemctl
          - sudo
        update_cache: true
        state: present

    - name: "Include neverneband.sssd_ldap"
      ansible.builtin.include_role:
        name: "neverneband.sssd_ldap"
