---
- name: Converge
  hosts: all
  tasks:
    - name: "systemctl and sudo install"
      ansible.builtin.apt:
        name: 
          - systemctl
          - sudo
        update_cache: true
        state: present

    - name: "Include neverneband.sssd_ldap"
      include_role:
        name: "neverneband.sssd_ldap"
