---
- name: Restart node_exporter service
  block:

    - name: Restart service
      ansible.builtin.systemd:
        name: node-exporter.service
        state: restarted
        enabled: true
      become: true
      register: service

    - name: Service assertion
      ansible.builtin.assert:
        that: service.status.ActiveState == "active"
