---

- name: Restart node_exporter service
  ansible.builtin.systemd:
    name: node-exporter.service
    state: restarted
    daemon_reload: true
    enabled: true
  become: true
  register: service
