---
# User setting
- name: Create prometheus group
  ansible.builtin.group:
    name: prometheus
    system: true
    state: present
  become: true

- name: Create prometheus user
  ansible.builtin.user:
    name: prometheus
    comment: prometheus
    group: prometheus
    shell: /sbin/nologin
    system: true
    create_home: false
  become: true

- name: Download node_exporter binary
  ansible.builtin.get_url:
    url: "{{ node_exporter_bin_dl_file }}"
    dest: /tmp/
    mode: "0644"
    owner: prometheus
    group: prometheus
  register: dl_node_ex_bin
  become: true

- name: Unarchive node_exporter binary
  ansible.builtin.unarchive:
    src: "{{ dl_node_ex_bin.dest }}"
    dest: "/tmp/"
    owner: prometheus
    group: prometheus
    remote_src: true
  become: true

- name: Copy binary files
  ansible.builtin.copy:
    src: "/tmp/{{ node_exporter_bin_file }}/{{ item }}"
    dest: "{{ node_exporter_install_path }}/{{ item }}"
    mode: "0744"
    owner: prometheus
    group: prometheus
    remote_src: true
  become: true
  loop:
    - node_exporter

- name: Send file node_exporter.service
  ansible.builtin.template:
    mode: "0644"
    src: node-exporter.service.j2
    dest: /etc/systemd/system/node-exporter.service
  become: true
  notify:
    - Restart node_exporter service
