---
- name: Configure SSSD
  tags:
    - configure
    - configure_sssd
    - sssd
  block:
    - name: Copy file /etc/sssd/sssd.conf
      ansible.builtin.copy:
        mode: "0600"
        src: sssd.conf
        dest: /etc/sssd/sssd.conf
      become: true
      notify:
        - Restart SSSD deamon
      register: copy_file_sssd_config

    - name: Copy file /etc/ssh/sshd_config.d/10-sshd-sssd.conf
      ansible.builtin.copy:
        mode: "0644"
        src: 10-sshd-sssd.conf
        dest: /etc/ssh/sshd_config.d/10-sshd-sssd.conf
      become: true
      notify:
        - Restart sshd deamon
      register: copy_file_sshd_config

    - name: PAM add mkhomedir
      community.general.pamd:
        name: common-session
        state: after
        type: session
        control: optional
        module_path: pam_systemd.so
        new_type: session
        new_control: optional
        new_module_path: pam_mkhomedir.so
      become: true

- name: Configure Goss
  tags:
    - configure
    - configure_goss
    - goss
  block:
    - name: Include Goss add file role
      ansible.builtin.include_role:
        name: install_goss
