---
- name: Copy file goss
  ansible.builtin.copy:
    src: goss
    dest: /usr/local/bin/goss
    mode: "0755"
  become: true

- name: Create goss directory
  ansible.builtin.file:
    path: "{{ goss_dir }}"
    state: directory
    mode: "0755"
  become: true

- name: Copy file goss
  ansible.builtin.copy:
    src: goss_main.yml
    dest: "{{ goss_dir }}/goss_main.yml"
    mode: "0755"
  become: true

- name: Test Goss
  ansible.builtin.command:
    cmd: "goss --gossfile {{ goss_dir }}/goss_main.yml validate --format json"
  register: goss_result
  ignore_errors: true
  become: true
  changed_when: goss_result.rc != 0

- name: Incloude output_report
  ansible.builtin.include_tasks:
    file: output_report.yml
